### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by SLAB-8002** [ragibson/SMS-MMS-deduplication#1]
I encountered this error when running your script:
```
Reading 'sms-20240121003902.xml'... Done in 17.7 s.
Preparing log file 'sms-20240121003902_deduplication.log'.
Searching for duplicates... Traceback (most recent call last):
  File "C:\Users\cfben\OneDrive\Apps\SMS Backup and Restore\dedupe_texts.py", line 210, in <module>
    output_tree, input_message_counts, output_message_counts = deduplicate_messages_in_tree(input_tree, log_file)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cfben\OneDrive\Apps\SMS Backup and Restore\dedupe_texts.py", line 132, in deduplicate_messages_in_tree
    remove_element(child, child_tag, child_attributes, child_attributes)
  File "C:\Users\cfben\OneDrive\Apps\SMS Backup and Restore\dedupe_texts.py", line 120, in remove_element
    log_file.write(removal_summary(element_tag, element_attributes, attribute_match))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f44d' in position 214: character maps to <undefined>
```

I was able to fix it by changing line 207 from `with open(log_fp, "w") as log_file:` to `with open(log_fp, "w", encoding="utf-8") as log_file:`.

**Comment by ragibson** [comment]
Interesting, are you running this on a Windows machine?
