### ISSUE TITLE
RuntimeError: Encountered SMIL data not captured by existing check?

### ISSUE THREAD

**Issue by Saijin-Naib** [ragibson/SMS-MMS-deduplication#5]
```
python3 ./dedupe_texts.py --ignore-date-milliseconds --ignore-whitespace-differences ~/sms-2023-05-09_01-04-44.xml/sms-2023-05-09_01-04-44.xml ~/sms-2023-05-09_01-04-44.xml/cleaned.xml ~/sms
-2023-05-09_01-04-44.xml/log.log
Reading '/home/USERNAME/sms-2023-05-09_01-04-44.xml/sms-2023-05-09_01-04-44.xml'... Done in 160.8 s.
Preparing log file '/home/USERNAME/sms-2023-05-09_01-04-44.xml/log.log'.
Searching for duplicates... Traceback (most recent call last):
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 295, in <module>
    output_tree, input_message_counts, output_message_counts = deduplicate_messages_in_tree(input_tree, log_file,
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 211, in deduplicate_messages_in_tree
    child_tag, child_attributes = retrieve_message_properties_and_tag(child, args)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 188, in retrieve_message_properties_and_tag
    child_tag, child_attributes = child.tag, retrieve_message_properties(child, args)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 131, in retrieve_message_properties
    result = tuple(item for element in [child] + list(child.iter()) for item in compile_relevant_fields(element))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 131, in <genexpr>
    result = tuple(item for element in [child] + list(child.iter()) for item in compile_relevant_fields(element))
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 123, in compile_relevant_fields
    return tuple(
           ^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 128, in <genexpr>
    and not contains_smil(element.attrib[field])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 74, in contains_smil
    raise RuntimeError(f"Encountered SMIL data not captured by existing check? {repr(s)}")
RuntimeError: Encountered SMIL data not captured by existing check? '<?xml version="1.0" encoding="UTF-8"?><smil>\r\n<head>\r\n<layout>\r\n<root-layout/>\r\n<region id="Text" top="70%" left="0%" height="30%" width="100%" fit="scroll"/>\r\n<region id="Image" top="0%" left="0%" height="70%" width="100%" fit="meet"/>\r\n</layout>\r\n</head>\r\n<body>\r\n<par dur="10s">\r\n<img src="imagejpeg_0.jpg" region="Image"/>\r\n</par>\r\n</body>\r\n</smil>'
```

This is reading a 18GBish backup that has been handed across from Windows Phone 8 -> Windows Phone 8.1 -> Windows 10 Mobile -> Android 9 -> Android 10 -> Android 11 -> Android 12 (LineageOS).

I am not surprised this backup isn't playing nice, but it does work on-device well, if that helps at all.

**Comment by ragibson** [comment]
Weird, your SMIL data is formated as an XML file rather than just a single tag.

I can probably take a shot at fixing this tonight.

**Comment by ragibson** [comment]
I've made a change (and added a test case) to address this issue.

Let me know if you run into any further issues -- a 18GB backup is about 5x larger than anything I've run personally.

**Comment by Saijin-Naib** [comment]
I'll pull the latest and test tonight. 

Thanks so much!

**Comment by Saijin-Naib** [comment]
This is what happens on the latest version:  
```
python3 ./dedupe_texts.py --ignore-date-milliseconds
 --ignore-whitespace-differences ~/sms-2023-05-09_01-04-44.xml/sms-2023-05-09_01-04-44.xml ~/sms-202
3-05-09_01-04-44.xml/cleaned.xml ~/sms-2023-05-09_01-04-44.xml/log.log
Reading '/home/BEC/sms-2023-05-09_01-04-44.xml/sms-2023-05-09_01-04-44.xml'... Done in 166.8 s.
Preparing log file '/home/BEC/sms-2023-05-09_01-04-44.xml/log.log'.
Searching for duplicates... Traceback (most recent call last):
  File "/home/BEC/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 303, in <module>
    output_tree, input_message_counts, output_message_counts = deduplicate_messages_in_tree(input_tree, log_file,
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/BEC/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 219, in deduplicate_messages_in_tree
    child_tag, child_attributes = retrieve_message_properties_and_tag(child, args)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/BEC/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 196, in retrieve_message_properties_and_tag
    child_tag, child_attributes = child.tag, retrieve_message_properties(child, args)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/BEC/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 139, in retrieve_message_properties
    result = tuple(item for element in [child] + list(child.iter()) for item in compile_relevant_fields(element))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/BEC/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 139, in <genexpr>
    result = tuple(item for element in [child] + list(child.iter()) for item in compile_relevant_fields(element))
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/BEC/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 131, in compile_relevant_fields
    return tuple(
           ^^^^^^
  File "/home/BEC/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 136, in <genexpr>
    and not contains_smil(element.attrib[field])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/BEC/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 81, in contains_smil
    raise RuntimeError(f"This SMIL format is unique / previously unknown and "
RuntimeError: This SMIL format is unique / previously unknown and not captured by the existing check? Please report: '\n<smil baseProfile="UnifiedMobile" id="root" version="3.0" xml:id="root" xmlns="http://www.w3.org/ns/SMIL">\n<head id="head" xml:id="head">\n<layout>\n<root-layout height="100%" width="100%"/>\n</layout>\n</head>\n<body xml:id="body">\n<par>\n<img begin="0" src="cid:IMAGE1.jpg"/>\n</par>\n<par>\n<text begin="0" src="cid:TEXT2.txt"/>\n</par>\n</body>\n</smil>'
```

**Comment by Saijin-Naib** [comment]
This is the message against the current build:  
```
python3 ./dedupe_texts.py --ignore-date-milliseconds
 --ignore-whitespace-differences ~/sms-2023-05-09_01-04-44.xml/sms-2023-05-09_01-04-44.xml ~/sms-202
3-05-09_01-04-44.xml/cleaned.xml ~/sms-2023-05-09_01-04-44.xml/log.log
Reading '/home/USERNAME/sms-2023-05-09_01-04-44.xml/sms-2023-05-09_01-04-44.xml'... Done in 166.8 s.
Preparing log file '/home/USERNAME/sms-2023-05-09_01-04-44.xml/log.log'.
Searching for duplicates... Traceback (most recent call last):
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 303, in <module>
    output_tree, input_message_counts, output_message_counts = deduplicate_messages_in_tree(input_tree, log_file,
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 219, in deduplicate_messages_in_tree
    child_tag, child_attributes = retrieve_message_properties_and_tag(child, args)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 196, in retrieve_message_properties_and_tag
    child_tag, child_attributes = child.tag, retrieve_message_properties(child, args)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 139, in retrieve_message_properties
    result = tuple(item for element in [child] + list(child.iter()) for item in compile_relevant_fields(element))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 139, in <genexpr>
    result = tuple(item for element in [child] + list(child.iter()) for item in compile_relevant_fields(element))
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 131, in compile_relevant_fields
    return tuple(
           ^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 136, in <genexpr>
    and not contains_smil(element.attrib[field])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USERNAME/Sources/SMS-MMS-deduplication/./dedupe_texts.py", line 81, in contains_smil
    raise RuntimeError(f"This SMIL format is unique / previously unknown and "
RuntimeError: This SMIL format is unique / previously unknown and not captured by the existing check? Please report: '\n<smil baseProfile="UnifiedMobile" id="root" version="3.0" xml:id="root" xmlns="http://www.w3.org/ns/SMIL">\n<head id="head" xml:id="head">\n<layout>\n<root-layout height="100%" width="100%"/>\n</layout>\n</head>\n<body xml:id="body">\n<par>\n<img begin="0" src="cid:IMAGE1.jpg"/>\n</par>\n<par>\n<text begin="0" src="cid:TEXT2.txt"/>\n</par>\n</body>\n</smil>'
```

**Comment by ragibson** [comment]
I see, you've got a newline after the XML declaration -- try the tweak I just pushed.

**Comment by ragibson** [comment]
Yeah, I wasn't thinking about memory usage too much when I initially wrote this. Glad it worked though! 😅

I'd bet it ends up requesting somewhere around an extra 1x-2x the input file size in keeping track of what it's seen so far during deduplication.
