### ISSUE TITLE
Error while deduping, "This SMIL format is unique / previously unknown and"

### ISSUE THREAD

**Issue by NessDan** [ragibson/SMS-MMS-deduplication#7]
Error below:

```
➜  SMS-MMS-deduplication git:(main) ✗ python3 dedupe_texts.py /mnt/c/Users/danie/Downloads/sms-20240919155114.xml/sms-20240919155114.xml /mnt/c/Users/danie/Downloads/sms-20240919155114.xml/sms-20240919155114.dedupe.xml
Reading '/mnt/c/Users/danie/Downloads/sms-20240919155114.xml/sms-20240919155114.xml'... Done in 61.5 s.
Preparing log file '/mnt/c/Users/danie/Downloads/sms-20240919155114.xml/sms-20240919155114_deduplication.log'.
Searching for duplicates... Traceback (most recent call last):
  File "/mnt/c/Users/danie/Documents/Code/SMS-MMS-deduplication/dedupe_texts.py", line 304, in <module>
    output_tree, input_message_counts, output_message_counts = deduplicate_messages_in_tree(input_tree, log_file,
  File "/mnt/c/Users/danie/Documents/Code/SMS-MMS-deduplication/dedupe_texts.py", line 220, in deduplicate_messages_in_tree
    child_tag, child_attributes = retrieve_message_properties_and_tag(child, args)
  File "/mnt/c/Users/danie/Documents/Code/SMS-MMS-deduplication/dedupe_texts.py", line 197, in retrieve_message_properties_and_tag
    child_tag, child_attributes = child.tag, retrieve_message_properties(child, args)
  File "/mnt/c/Users/danie/Documents/Code/SMS-MMS-deduplication/dedupe_texts.py", line 140, in retrieve_message_properties
    result = tuple(item for element in [child] + list(child.iter()) for item in compile_relevant_fields(element))
  File "/mnt/c/Users/danie/Documents/Code/SMS-MMS-deduplication/dedupe_texts.py", line 140, in <genexpr>
    result = tuple(item for element in [child] + list(child.iter()) for item in compile_relevant_fields(element))
  File "/mnt/c/Users/danie/Documents/Code/SMS-MMS-deduplication/dedupe_texts.py", line 132, in compile_relevant_fields
    return tuple(
  File "/mnt/c/Users/danie/Documents/Code/SMS-MMS-deduplication/dedupe_texts.py", line 137, in <genexpr>
    and not contains_smil(element.attrib[field])
  File "/mnt/c/Users/danie/Documents/Code/SMS-MMS-deduplication/dedupe_texts.py", line 82, in contains_smil
    raise RuntimeError(f"This SMIL format is unique / previously unknown and "
RuntimeError: This SMIL format is unique / previously unknown and not captured by the existing check? Please report: '<!DOCTYPE smil PUBLIC "-//W3C//DTD SMIL 2.0//EN" "http://www.w3.org/2001/SMIL20/SMIL20.dtd">\r\n<smil xmlns="http://www.w3.org/2001/SMIL20/Language">\r\n<head>\r\n<layout>\r\n<root-layout width="100%" height="100%"/>\r\n<region id="MediaAttachment"  />\r\n<region id="Text" />\r\n</layout>\r\n</head>\r\n<body>\r\n<par>\r\n<image src="cid:AOC_Parler_MMS.jpg"ref region="MediaAttachment"/>\r\n<text src="cid:mmstext.txt" region="Text"/>\r\n</par>\r\n</body>\r\n</smil>'
```

**Comment by ragibson** [comment]
That _is_ a bit of weird SMIL format -- I think I can probably fix this tonight or tomorrow

**Comment by NessDan** [comment]
You're the best @ragibson ! Let me know if I can help in any way 🙏

**Comment by NessDan** [comment]
FYI I know AI gets a bad rep, but I used the newest OpenAI reasoning model on this issue and it came up with a solution that helped me get past the error and outputted a deduplicated XML file.

```
➜  SMS-MMS-deduplication git:(main) ✗ python3 dedupe_texts.py /mnt/c/Users/danie/Downloads/sms-20240919155114.xml/sms-20240919155114.xml /mnt/c/Users/danie/Downloads/sms-20240919155114.xml/sms-20240919155114.dedupe.xml
Reading '/mnt/c/Users/danie/Downloads/sms-20240919155114.xml/sms-20240919155114.xml'... Done in 56.4 s.
Preparing log file '/mnt/c/Users/danie/Downloads/sms-20240919155114.xml/sms-20240919155114_deduplication.log'.
Searching for duplicates... Done in 77.0 s.
Deduplication Summary:
    Message Type    |   Original Count   |      Removed       | Deduplicated Count 
        mms         |       59939        |         22         |       59917        
        sms         |       94907        |         2          |       94905        
Writing '/mnt/c/Users/danie/Downloads/sms-20240919155114.xml/sms-20240919155114.dedupe.xml'... Done in 17.9 s
➜  SMS-MMS-deduplication git:(main) ✗
```

Unsure if the code change it recommended is even good or just good enough to get past that one error, but here's what I got:

```python
def contains_smil(s):
    """Check if s contains SMIL data."""
    s = s.strip()
    # Remove XML declaration if it exists
    if s.startswith("<?xml") and "?>" in s:
        s = s[s.index("?>") + len("?>"):].strip()
    # Remove DOCTYPE declaration if it exists
    if s.startswith("<!DOCTYPE") and ">" in s:
        s = s[s.index(">") + 1:].strip()
    # Now check if it contains SMIL data
    return "<smil" in s and "</smil>" in s
```

[The discussion with ChatGPT is here.](https://chatgpt.com/share/66ed7e4a-a3b0-800b-ad85-9e5a7a5dd671)

**Comment by ragibson** [comment]
Interesting, the change it made isn't correct -- it seems to strip out the
whole opening tag once noticing the DOCTYPE portion, which would
erroneously miss the SMIL data (and it dropped the exception altogether so
the script could continue, but that was at your request).

As a temporary workaround, it's probably fine? Worst case, I'd expect a few
duplicates to not be removed if their SMIL data is formatted slightly
differently.

**Comment by ragibson** [comment]
o1's solutions was better than I first gave it credit for, (I thought it was stripping the whole SMIL tag in the DOCTYPE check).

I ended up implementing something pretty similar (plus tests) in https://github.com/ragibson/SMS-MMS-deduplication/commit/e5e613472d45859aad0a99af255ba04c950742f7.
